# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  JanelleInterpreter_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := JanelleInterpreter

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

JanelleInterpreter:
ifneq (,$(JanelleInterpreter_config))
	@echo "==== Building JanelleInterpreter ($(JanelleInterpreter_config)) ===="
	@${MAKE} --no-print-directory -C . -f JanelleInterpreter.make config=$(JanelleInterpreter_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f JanelleInterpreter.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   JanelleInterpreter"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"